/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventarium;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joaquin
 */
public class AdminPanelFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminPanelFrame
     */
    public AdminPanelFrame(String nombreUsuario) {
        initComponents();
        this.setSize(1200, 750);
        lblNombreUsuario.setText(nombreUsuario);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSuperior = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblAdmin = new javax.swing.JLabel();
        lblNombreUsuario = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        panelLateral = new javax.swing.JPanel();
        lblMenu = new javax.swing.JLabel();
        panelInventario = new javax.swing.JPanel();
        iconInven = new javax.swing.JLabel();
        lblInventario = new javax.swing.JLabel();
        btnUsuarios = new javax.swing.JButton();
        btnInformes = new javax.swing.JButton();
        btnImporExpor = new javax.swing.JButton();
        panelCentral = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbCategoria = new javax.swing.JComboBox<>();
        btnAlta = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnDarDeBaja = new javax.swing.JButton();
        btnLocalizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 700));

        panelSuperior.setBackground(new java.awt.Color(24, 95, 165));
        panelSuperior.setPreferredSize(new java.awt.Dimension(0, 50));
        panelSuperior.setLayout(new java.awt.BorderLayout());

        lblTitulo.setBackground(new java.awt.Color(255, 255, 255));
        lblTitulo.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/llavenBlanca.png"))); // NOI18N
        lblTitulo.setText("Gestión del Taller - IES Miguel Herrero Pereda");
        panelSuperior.add(lblTitulo, java.awt.BorderLayout.CENTER);

        jPanel1.setOpaque(false);

        lblAdmin.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lblAdmin.setForeground(new java.awt.Color(181, 212, 244));
        lblAdmin.setText("Admin:");
        jPanel1.add(lblAdmin);
        jPanel1.add(lblNombreUsuario);

        btnCerrarSesion.setBackground(new java.awt.Color(12, 60, 120));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/login.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrarSesion);

        panelSuperior.add(jPanel1, java.awt.BorderLayout.LINE_END);

        getContentPane().add(panelSuperior, java.awt.BorderLayout.PAGE_START);

        panelLateral.setBackground(new java.awt.Color(32, 37, 46));
        panelLateral.setPreferredSize(new java.awt.Dimension(190, 0));
        panelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMenu.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        lblMenu.setForeground(new java.awt.Color(140, 150, 168));
        lblMenu.setText("MENÚ");
        panelLateral.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, 160, 16));

        panelInventario.setBackground(new java.awt.Color(24, 95, 165));
        panelInventario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconInven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/caja.png"))); // NOI18N
        panelInventario.add(iconInven, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 16, 16));

        lblInventario.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblInventario.setForeground(new java.awt.Color(255, 255, 255));
        lblInventario.setText("Inventario");
        panelInventario.add(lblInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 12, 100, 16));

        panelLateral.add(panelInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 40, 174, 40));

        btnUsuarios.setBackground(new java.awt.Color(32, 37, 46));
        btnUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/users.png"))); // NOI18N
        btnUsuarios.setText("Usuarios");
        btnUsuarios.setBorderPainted(false);
        btnUsuarios.setContentAreaFilled(false);
        btnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuarios.setFocusPainted(false);
        btnUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        panelLateral.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 86, 174, 40));

        btnInformes.setBackground(new java.awt.Color(32, 37, 46));
        btnInformes.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnInformes.setForeground(new java.awt.Color(255, 255, 255));
        btnInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/archivo.png"))); // NOI18N
        btnInformes.setText("Informes");
        btnInformes.setBorderPainted(false);
        btnInformes.setContentAreaFilled(false);
        btnInformes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInformes.setFocusPainted(false);
        btnInformes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformesActionPerformed(evt);
            }
        });
        panelLateral.add(btnInformes, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 132, 174, 40));

        btnImporExpor.setBackground(new java.awt.Color(32, 37, 46));
        btnImporExpor.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnImporExpor.setForeground(new java.awt.Color(255, 255, 255));
        btnImporExpor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/iconoImporExport.png"))); // NOI18N
        btnImporExpor.setText("Importar/Exportar");
        btnImporExpor.setBorderPainted(false);
        btnImporExpor.setContentAreaFilled(false);
        btnImporExpor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImporExpor.setFocusPainted(false);
        btnImporExpor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        panelLateral.add(btnImporExpor, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 178, 174, 40));

        getContentPane().add(panelLateral, java.awt.BorderLayout.LINE_START);

        panelCentral.setBackground(new java.awt.Color(28, 32, 40));
        panelCentral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setBackground(new java.awt.Color(44, 50, 62));
        txtBuscar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(140, 150, 168));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        panelCentral.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 32));

        cmbEstado.setBackground(new java.awt.Color(44, 50, 62));
        cmbEstado.setForeground(new java.awt.Color(220, 225, 235));
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los estados", "Operativo", "Averiado", "En reparacion", "Obsoleto" }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });
        panelCentral.add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 150, 32));

        cmbCategoria.setBackground(new java.awt.Color(44, 50, 62));
        cmbCategoria.setForeground(new java.awt.Color(220, 225, 235));
        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las categorias", "PCs para practicas", "Componentes hardware", "Equipos de red", "Cableado estructurado", "Herramientas de soldadura y generales", "Material fungible" }));
        cmbCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCategoriaActionPerformed(evt);
            }
        });
        panelCentral.add(cmbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 180, 32));

        btnAlta.setBackground(new java.awt.Color(24, 95, 165));
        btnAlta.setForeground(new java.awt.Color(255, 255, 255));
        btnAlta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/plus.png"))); // NOI18N
        btnAlta.setText("Alta");
        btnAlta.setBorderPainted(false);
        btnAlta.setFocusPainted(false);
        btnAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltaActionPerformed(evt);
            }
        });
        panelCentral.add(btnAlta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 100, 32));

        btnEditar.setBackground(new java.awt.Color(44, 50, 62));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorderPainted(false);
        btnEditar.setFocusPainted(false);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        panelCentral.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 52, 100, 32));

        btnDarDeBaja.setBackground(new java.awt.Color(44, 50, 62));
        btnDarDeBaja.setForeground(new java.awt.Color(255, 255, 255));
        btnDarDeBaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/basuraEnBlanco.png"))); // NOI18N
        btnDarDeBaja.setText("Dar de baja");
        btnDarDeBaja.setBorderPainted(false);
        btnDarDeBaja.setFocusPainted(false);
        btnDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDarDeBajaActionPerformed(evt);
            }
        });
        panelCentral.add(btnDarDeBaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 52, 110, 32));

        btnLocalizar.setBackground(new java.awt.Color(44, 50, 62));
        btnLocalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/location.png"))); // NOI18N
        btnLocalizar.setText("Localizar");
        btnLocalizar.setBorderPainted(false);
        btnLocalizar.setFocusPainted(false);
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });
        panelCentral.add(btnLocalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 52, 100, 32));

        tablaInventario.setBackground(new java.awt.Color(36, 41, 51));
        tablaInventario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tablaInventario.setForeground(new java.awt.Color(220, 225, 235));
        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria", "Estado", "Cantidad", "Ubicacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInventario.setGridColor(new java.awt.Color(60, 68, 85));
        tablaInventario.setRowHeight(30);
        tablaInventario.setSelectionBackground(new java.awt.Color(12, 60, 120));
        tablaInventario.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablaInventario.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tablaInventario);

        panelCentral.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 950, 530));

        getContentPane().add(panelCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void cargarTabla() {
            
        String[] columnas = {"ID", "Nombre", "Categoría", "Estado", "Cantidad", "Ubicación"};

        DefaultTableModel tabla = new DefaultTableModel(columnas, 0);// 0 filas iniciales

            String sql = "SELECT m.id_material, m.nombre, m.descripcion, c.nombre as categoria, " +
                         "e.nombre as estado, m.cantidad, m.id_ubicacion " +
                         "FROM material m " +
                         "JOIN categorias c ON c.id_categoria = m.id_categoria " +
                         "JOIN estado e ON e.id_estado = m.id_estado";

            try (PreparedStatement ps = AccesoBaseDatos.getInstance().getConn().prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) {

                while (rs.next()) {
                    tabla.addRow(new Object[]{
                        rs.getInt("id_material"),
                        rs.getString("nombre"),
                        rs.getString("descripcion"),
                        rs.getString("categoria"),
                        rs.getString("estado"),
                        rs.getInt("cantidad"),
                        rs.getInt("id_ubicacion")
                    });
                }

            } catch (SQLException e) {
                System.out.println("SQL ERROR -> " + e.getMessage());
            }

        tablaInventario.setModel(tabla);// muestra los datos que metes en 'tabla'
    }
    
    
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        
        dispose();
        
        new LoginFrame().setVisible(true);
        
        
        
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDarDeBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDarDeBajaActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocalizarActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void btnInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInformesActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        
        UsuariosDialog usersDialog = new UsuariosDialog(this, true);
        usersDialog.setLocationRelativeTo(this); // para que se abra centrado
        usersDialog.setVisible(true); // muestra el dialogo
        
    }//GEN-LAST:event_btnUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanelFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String nombre = null;
                new AdminPanelFrame(nombre).setVisible(true);

            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnDarDeBaja;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnImporExpor;
    private javax.swing.JButton btnInformes;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JLabel iconInven;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdmin;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelCentral;
    private javax.swing.JPanel panelInventario;
    private javax.swing.JPanel panelLateral;
    private javax.swing.JPanel panelSuperior;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
