/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventarium;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Joaquin
 */
public class ProfesorFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfesorFrame
     */
    public ProfesorFrame(String nombre) {
        initComponents();
        txtProfesorNombre.setText(nombre);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtProfesorNombre = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnLocalizar = new javax.swing.JButton();
        btnListado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInventario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 700));

        jPanel1.setBackground(new java.awt.Color(15, 110, 86));
        jPanel1.setPreferredSize(new java.awt.Dimension(0, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/llave.png"))); // NOI18N
        jLabel1.setText("Gestión del Taller - IES Miguel Herrero Pereda");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.setOpaque(false);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(159, 225, 203));
        jLabel2.setText("Profesor:");
        jPanel2.add(jLabel2);

        txtProfesorNombre.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jPanel2.add(txtProfesorNombre);

        btnCerrarSesion.setBackground(new java.awt.Color(8, 55, 43));
        btnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/login.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar sesión");
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setFocusPainted(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrarSesion);

        jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(28, 32, 40));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(44, 50, 62));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(140, 150, 168));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 32));

        jComboBox1.setBackground(new java.awt.Color(44, 50, 62));
        jComboBox1.setForeground(new java.awt.Color(220, 225, 235));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos los estados", "Operativo", "Averiado", "En reparacion", "Obsoleto" }));
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 150, 32));

        jComboBox2.setBackground(new java.awt.Color(44, 50, 62));
        jComboBox2.setForeground(new java.awt.Color(220, 225, 235));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las categorías", "PCs para prácticas", "Componentes hardware", "Equipos de red", "Cableado estructurado", "Herramientas de soldadura y generales", "Material fungible" }));
        jPanel3.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 180, 32));

        btnLocalizar.setBackground(new java.awt.Color(15, 110, 86));
        btnLocalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnLocalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/location.png"))); // NOI18N
        btnLocalizar.setText("Localizar en la web");
        btnLocalizar.setBorderPainted(false);
        btnLocalizar.setFocusPainted(false);
        btnLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocalizarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLocalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, 160, 32));

        btnListado.setBackground(new java.awt.Color(44, 50, 62));
        btnListado.setForeground(new java.awt.Color(255, 255, 255));
        btnListado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/archivo.png"))); // NOI18N
        btnListado.setText("Generar listado");
        btnListado.setBorderPainted(false);
        btnListado.setFocusPainted(false);
        jPanel3.add(btnListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 52, 130, 32));

        tablaInventario.setBackground(new java.awt.Color(36, 41, 51));
        tablaInventario.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tablaInventario.setForeground(new java.awt.Color(220, 225, 235));
        tablaInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Estado", "Cantidad", "Ubicación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaInventario.setEnabled(false);
        tablaInventario.setGridColor(new java.awt.Color(60, 68, 85));
        tablaInventario.setRowHeight(30);
        tablaInventario.setSelectionBackground(new java.awt.Color(12, 60, 120));
        tablaInventario.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tablaInventario.setShowHorizontalLines(true);
        jScrollPane1.setViewportView(tablaInventario);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, 760, 480));

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        private void cargarTabla() {
            
        String[] columnas = {"ID", "Nombre", "Categoría", "Estado", "Cantidad", "Ubicación"};

        DefaultTableModel tabla = new DefaultTableModel(columnas, 0);// 0 filas iniciales

        String sql = "SELECT m.id_material, m.nombre, m.descripcion, c.nombre as categoria, " +
                         "e.nombre as estado, m.cantidad, m.id_ubicacion " +
                         "FROM material m " +
                         "JOIN categorias c ON c.id_categoria = m.id_categoria " +
                         "JOIN estado e ON e.id_estado = m.id_estado "  +
                         "JOIN ubicaciones u ON u.codigo_armario = m.id_ubicacion";

            try (PreparedStatement ps = AccesoBaseDatos.getInstance().getConn().prepareStatement(sql);
                 ResultSet rs = ps.executeQuery()) {

                while (rs.next()) {
                    tabla.addRow(new Object[]{
                        rs.getInt("id_material"),
                        rs.getString("nombre"),
                        rs.getString("descripcion"),
                        rs.getString("categoria"),
                        rs.getString("estado"),
                        rs.getInt("cantidad"),
                        rs.getInt("espacio")
                    });
                }

            } catch (SQLException e) {
                System.out.println("SQL ERROR -> " + e.getMessage());
            }

        tablaInventario.setModel(tabla);// muestra los datos que metes en 'tabla'
    }
    
    
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLocalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfesorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfesorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfesorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfesorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String nombre = null;
                new ProfesorFrame(nombre).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnListado;
    private javax.swing.JButton btnLocalizar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaInventario;
    private javax.swing.JLabel txtProfesorNombre;
    // End of variables declaration//GEN-END:variables
}
